server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false
    username: root
    password: Lutong~918
  application:
    # 服务名称
    name: user-center
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848
        # 命名空间 dev
        # namespace: 6b0e9c31-3145-411d-bf5f-439f90a03ad2
        # BJ
        cluster-name: BJ
        # 元数据信息配置文件配置,也可以nacos控制台配置，版本控制
        # metadata:
          # instance: c
          # haha: hehe
          # version: v1
