server:
  port: 8080
spring:
  zipkin:
    base-url: http://localhost:9411/
    # 关闭服务发现,解决异常 http://www.imooc.com/article/291578
    discoveryClientEnabled: false
    # 这个启动命令可以持久化数据到ES当然也支持mysql不过要注意性能问题 STORAGE_TYPE=elasticsearch ES_HOST=localhost:9200 java -jar
    # 数据持久化之后发现 服务依赖图不能看，需要下载github上官方zipKin-dependency包,环境变量「STORAGE_TYPE, ES_HOST, ES_INDEX默认zipkin」
  sleuth:
    sampler:
      # 抽样率1.0 = 100% 上报所有,默认1.0 , 抽样降低对应用性能对影响
      probability: 1.0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false
    username: root
    password: Lutong~918
  application:
    # 服务名称
    name: user-center
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848
        # 命名空间 dev
        namespace: 6b0e9c31-3145-411d-bf5f-439f90a03ad2
        # BJ
        cluster-name: BJ
        # 元数据信息配置文件配置,也可以nacos控制台配置，版本控制
        metadata:
          version: v1
    # 消息通信stream流
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: stream-test-topic
          # 用rocketmq必须设置
          group: binder-group
        my-input:
          destination: stream-my-topic
          # 用rocketmq必须设置
          group: my-group

# rocket消息队列
rocketmq:
  name-server: 127.0.0.1:9876

# 日志
logging:
  level:
    # 只打印error级别的日志
    com.alibaba.nacos: error
    org.spring.framwork.cloud.sleuth: debug

#JWT密钥配置
jwt:
  secret: MQj3al5#jH&9@notebylothar
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600


